using SatisfactoryProductionator.DataModels.Enums;

namespace SatisfactoryProductionator.DataConverter
{
	public static class Constants
	{
		public static readonly string JSON_FILEPATH = @"data/docs.json";
		public static readonly string RAW_RESOURCES =  "Resources/RawResources";
		public static readonly string PARTS = "Resource/Parts";
		public static readonly string XMAS = "Christmas";
		public static readonly string BUILDING_ONE_INDEX = "Factory/";
		public static readonly string BUILDING_TWO_INDEX = "/";
		public static readonly string ITEM_SPLIT = "),(";
		public static readonly string ITEM_SPLIT_COMMA = ",";
		public static readonly string ITEM_QUANTITY_SPLIT = @"""',Amount=";
		public static readonly string ITEM_INDEX_ONE = ".";
		public static readonly string ITEM_INDEX_TWO = "_C";

		public static readonly List<string> ITEM_CLASSES = new()
		{
			"Class'/Script/FactoryGame.FGItemDescriptor'",
			"Class'/Script/FactoryGame.FGItemDescriptorBiomass'",
			"Class'/Script/FactoryGame.FGResourceDescriptor'",
			"Class'/Script/FactoryGame.FGItemDescriptorNuclearFuel'",
			"Class'/Script/FactoryGame.FGAmmoTypeProjectile'",
			"Class'/Script/FactoryGame.FGAmmoTypeSpreadshot'",
			"Class'/Script/FactoryGame.FGAmmoTypeInstantHit'",
			"Class'/Script/FactoryGame.FGConsumableDescriptor'",
			"Class'/Script/FactoryGame.FGEquipmentDescriptor'",
		};

		public static readonly List<(string className, BuildingType buildingType)> BUILDING_CLASSES = new()
		{
			("Class'/Script/FactoryGame.FGBuildableResourceExtractor'", BuildingType.Extractor),
			("Class'/Script/FactoryGame.FGBuildableFrackingActivator'", BuildingType.Extractor),
			("Class'/Script/FactoryGame.FGBuildableFrackingExtractor'", BuildingType.Extractor),
			("Class'/Script/FactoryGame.FGBuildableWaterPump'", BuildingType.Extractor),
			("Class'/Script/FactoryGame.FGBuildableManufacturer'", BuildingType.Manufacturer),
			("Class'/Script/FactoryGame.FGBuildableManufacturerVariablePower'", BuildingType.VariableManufacturer),
			("Class'/Script/FactoryGame.FGBuildableGeneratorGeoThermal'", BuildingType.Generator),
			("Class'/Script/FactoryGame.FGBuildableGeneratorFuel'", BuildingType.Generator),
			("Class'/Script/FactoryGame.FGBuildableGeneratorNuclear'", BuildingType.Generator),

		};

		public static readonly List<string> ITEM_FILTER = new()
		{
			"FICSMAS Gift",
			"Candy Cane",
			"FICSMAS Tree Branch",
			"FICSMAS Bow",
			"Actual Snow",
			"FICSMAS Decoration",
			"FICSMAS Ornament Bundle",
			"Iron FICSMAS Ornament",
			"Copper FICSMAS Ornament",
			"Blue FICSMAS Ornament",
			"Red FICSMAS Ornament",
			"FICSMAS Wonder Star",
			"HUB Parts",
			"Sweet Fireworks",
			"Fancy Fireworks",
			"Sparkly Fireworks",
			"Snowball",
			"Chainsaw",
			"Factory Cart\u2122",
			"Hazmat Suit",
			"Jetpack",
			"Blade Runners",
			"Rebar Gun",
			"Rifle",
			"Xeno-Zapper",
			"Xeno-Basher",
			"Nobelisk Detonator",
			"Object Scanner",
			"Gas Mask",
			"Hover Pack",
			"Zipline",
			"Candy Cane Basher",
			"Golden Factory Cart\u2122",
		};

		public static readonly Dictionary<string, string> CATEGORY_MAP = new()
		{
			{ "Portable Miner", "Special"},
			{ "Blue Power Slug", "Special" },
			{ "Yellow Power Slug", "Special" },
			{ "Purple Power Slug", "Special" },
			{ "Power Shard", "Special" },
			{ "Adaptive Control Unit", "Space Parts" },
			{ "AI Limiter", "Electronics" },
			{ "Alclad Aluminum Sheet", "Standard Parts" },
			{ "Alien DNA Capsule", "Alien" },
			{ "Alien Protein", "Alien" },
			{ "Alumina Solution", "Liquids" },
			{ "Aluminum Casing", "Standard Parts" },
			{ "Aluminum Ingot", "Ingots" },
			{ "Aluminum Scrap", "Minerals" },
			{ "Assembly Director System", "Space Parts" },
			{ "Automated Wiring", "Space Parts" },
			{ "Bacon Agaric", "Consumables" },
			{ "Battery", "Electronics" },
			{ "Bauxite", "Ores" },
			{ "Beacon", "Consumables" },
			{ "Beryl Nut", "Consumables" },
			{ "Biomass", "Fuels" },
			{ "Black Powder", "Minerals" },
			{ "Cable", "Electronics" },
			{ "Caterium Ingot", "Ingots" },
			{ "Caterium Ore", "Ores" },
			{ "Circuit Board", "Electronics" },
			{ "Cluster Nobelisk", "Ammos" },
			{ "Coal", "Ores" },
			{ "Color Cartridge", "Consumables" },
			{ "Compacted Coal", "Minerals" },
			{ "Computer", "Communications" },
			{ "Concrete", "Minerals" },
			{ "Cooling System", "Industrial Parts" },
			{ "Copper Ingot", "Ingots" },
			{ "Copper Ore", "Ores" },
			{ "Copper Powder", "Minerals" },
			{ "Copper Sheet", "Standard Parts" },
			{ "Crude Oil", "Liquids" },
			{ "Crystal Oscillator", "Communications" },
			{ "Electromagnetic Control Rod", "Electronics" },
			{ "Empty Canister", "Containers" },
			{ "Empty Fluid Tank", "Containers" },
			{ "Encased Industrial Beam", "Standard Parts" },
			{ "Encased Plutonium Cell", "Nuclear" },
			{ "Encased Uranium Cell", "Nuclear" },
			{ "Explosive Rebar", "Ammos" },
			{ "Fabric", "Standard Parts" },
			{ "Flower Petals", "Fuels" },
			{ "Fuel", "Liquids" },
			{ "Fused Modular Frame", "Standard Parts" },
			{ "Gas Filter", "Consumables" },
			{ "Gas Nobelisk", "Ammos" },
			{ "Hatcher Remains", "Alien" },
			{ "Heat Sink", "Industrial Parts" },
			{ "Heavy Modular Frame", "Standard Parts" },
			{ "Heavy Oil Residue", "Liquids" },
			{ "High-Speed Connector", "Electronics" },
			{ "Hog Remains", "Alien" },
			{ "Homing Rifle Ammo", "Ammos" },
			{ "Iodine Infused Filter", "Consumables" },
			{ "Iron Ingot", "Ingots" },
			{ "Iron Ore", "Ores" },
			{ "Iron Plate", "Standard Parts" },
			{ "Iron Rebar", "Ammos" },
			{ "Iron Rod", "Standard Parts" },
			{ "Leaves", "Fuels" },
			{ "Limestone", "Ores" },
			{ "Liquid Biofuel", "Liquids" },
			{ "Magnetic Field Generator", "Space Parts" },
			{ "Medicinal Inhaler", "Consumables" },
			{ "Modular Engine", "Space Parts" },
			{ "Modular Frame", "Standard Parts" },
			{ "Motor", "Industrial Parts" },
			{ "Mycelia", "Fuels" },
			{ "Nitric Acid", "Liquids" },
			{ "Nitrogen Gas", "Gas" },
			{ "Nobelisk", "Ammos" },
			{ "Non-fissile Uranium", "Nuclear" },
			{ "Nuclear Pasta", "Nuclear" },
			{ "Nuke Nobelisk", "Ammos" },
			{ "Packaged Alumina Solution", "Containers" },
			{ "Packaged Fuel", "Fuels" },
			{ "Packaged Heavy Oil Residue", "Fuels" },
			{ "Packaged Liquid Biofuel", "Fuels" },
			{ "Packaged Nitric Acid", "Containers" },
			{ "Packaged Nitrogen Gas", "Containers" },
			{ "Packaged Oil", "Fuels" },
			{ "Packaged Sulfuric Acid", "Containers" },
			{ "Packaged Turbofuel", "Fuels" },
			{ "Packaged Water", "Containers" },
			{ "Paleberry", "Consumables" },
			{ "Parachute", "Consumables" },
			{ "Petroleum Coke", "Oil Products" },
			{ "Plasma Spitter Remains", "Alien" },
			{ "Plastic", "Oil Products" },
			{ "Plutonium Fuel Rod", "Fuels" },
			{ "Plutonium Pellet", "Nuclear" },
			{ "Plutonium Waste", "Nuclear" },
			{ "Polymer Resin", "Oil Products" },
			{ "Pressure Conversion Cube", "Containers" },
			{ "Pulse Nobelisk", "Ammos" },
			{ "Quartz Crystal", "Minerals" },
			{ "Quickwire", "Electronics" },
			{ "Radio Control Unit", "Communications" },
			{ "Raw Quartz", "Ores" },
			{ "Reinforced Iron Plate", "Standard Parts" },
			{ "Rifle Ammo", "Ammos" },
			{ "Rotor", "Industrial Parts" },
			{ "Rubber", "Oil Products" },
			{ "Screw", "Standard Parts" },
			{ "Shatter Rebar", "Ammos" },
			{ "Silica", "Minerals" },
			{ "Smart Plating", "Space Parts" },
			{ "Smokeless Powder", "Minerals" },
			{ "Solid Biofuel", "Fuels" },
			{ "Stator", "Industrial Parts" },
			{ "Steel Beam", "Standard Parts" },
			{ "Steel Ingot", "Ingots" },
			{ "Steel Pipe", "Standard Parts" },
			{ "Stinger Remains", "Alien" },
			{ "Stun Rebar", "Ammos" },
			{ "Sulfur", "Ores" },
			{ "Sulfuric Acid", "Liquids" },
			{ "Supercomputer", "Communications" },
			{ "Thermal Propulsion Rocket", "Space Parts" },
			{ "Turbo Motor", "Industrial Parts" },
			{ "Turbo Rifle Ammo", "Ammos" },
			{ "Turbofuel", "Liquids" },
			{ "Uranium Fuel Rod", "Fuels" },
			{ "Uranium Waste", "Nuclear" },
			{ "Uranium", "Ores" },
			{ "Versatile Framework", "Space Parts" },
			{ "Water", "Liquids" },
			{ "Wire", "Electronics" },
			{ "Wood", "Fuels" },

		};

		public static readonly Dictionary<string, string> BUILDING_MAP = new()
		{
			{ "AssemblerMk1", "Assembler" },
			{ "Blender", "Blender" },
			{ "ConstructorMk1", "Constructor" },
			{ "Constructor", "Constructor" },
			{ "FoundryMk1", "Foundry" },
			{ "Foundry", "Foundry" },
			{ "HadronCollider", "Particle Accelerator" },
			{ "ManufacturerMk1", "Manufacturer" },
			{ "OilRefinery", "Refinery" },
			{ "Refinery", "Refinery" },
			{ "Packager", "Packager" },
			{ "SmelterMk1", "Smelter" },
			{ "Smelter", "Smelter" },
			{ "Miner Mk.1", "Miner Mk1" },
			{ "Miner Mk.2", "Miner Mk2" },
			{ "Miner Mk.3", "Miner Mk3" },
			{ "Oil Extractor", "Oil Extractor" },
			{ "Resource Well Pressurizer", "Resource Well Pressurizer" },
			{ "Water Extractor", "Water Extractor" },

		};

		public static readonly List<string> EXTRACTABLE_RESOURCES = new()
		{
			"Bauxite",
			"Caterium Ore",
			"Coal",
			"Copper Ore",
			"Crude Oil",
			"Iron Ore",
			"LimeStone",
			"Raw Quartz",
			"Sulfur",
			"Uranium",

		};

		public static readonly List<string> BIOMASS_FUELS = new()
		{
			"Hog Remains",
			"Plasma Spitter Remains",
			"Flower Petals",
			"Leaves",
			"Mycelia",
			"Wood",
			"Hatcher Remains",
			"Stinger Remains",
			"Solid Biofuel",
			"Packaged Liquid Biofuel",
			"Biomass",
			"Liquid Biofuel",
			"Packaged Alumina Solution",
			"Packaged Sulfuric Acid",
			"Packaged Nitrogen Gas",
			"Packaged Nitric Acid",
			"Fabric",
		};

		public static readonly Dictionary<string, string> SIZE_MAP = new()
		{
			{ "SS_FLUID", "Fluid" },
			{ "SS_ONE", "1" },
			{ "SS_SMALL", "50" },
			{ "SS_MEDIUM", "100" },
			{ "SS_BIG", "200" },
			{ "SS_HUGE", "500" },
		};
	}
}
